// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApp.Models;

public partial class Korisnik
{
    public int IdKorisnik { get; set; }

    public string Lozinka { get; set; }

    public string KorisnickoIme { get; set; }

    public string Ime { get; set; }

    public string Prezime { get; set; }

    public DateTime DatumRodenja { get; set; }

    public string Email { get; set; }

    public int BrojMobitela { get; set; }

    public int IdMjesto { get; set; }

    public int Admin { get; set; }

    public virtual Mjesto IdMjestoNavigation { get; set; }

    public virtual ICollection<Rezervacija> Rezervacijas { get; set; } = new List<Rezervacija>();
}