// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApp.Models;

public partial class Mjesto
{
    public int IdMjesto { get; set; }

    public string Naziv { get; set; }

    public int Postanskibroj { get; set; }

    public virtual ICollection<Korisnik> Korisniks { get; set; } = new List<Korisnik>();

    public virtual ICollection<Putovanje> Putovanjes { get; set; } = new List<Putovanje>();
}