// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApp.Models;

public partial class Putovanje
{
    public int IdPutovanja { get; set; }

    public int IdMjesto { get; set; }

    public int IdSmjestaj { get; set; }

    public int IdVrstaPutovanja { get; set; }

    public int IdVozilo { get; set; }

    public string Opis { get; set; }

    public string ImeprezimeVoditelj { get; set; }

    public int Cijena { get; set; }

    public DateTime DatumPolaska { get; set; }

    public DateTime DatumPovratka { get; set; }

    public byte[] Slika { get; set; }

    public string Rate { get; set; }

    public virtual Mjesto IdMjestoNavigation { get; set; }

    public virtual Smjestaj IdSmjestajNavigation { get; set; }

    public virtual Vozilo IdVoziloNavigation { get; set; }

    public virtual VrstaPutovanja IdVrstaPutovanjaNavigation { get; set; }

    public virtual ICollection<Rezervacija> Rezervacijas { get; set; } = new List<Rezervacija>();
}