// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApp.Models;

public partial class Rezervacija
{
    public int IdRezervacija { get; set; }

    public int IdKorisnik { get; set; }

    public int IdPutovanje { get; set; }

    public int Potvrdeno { get; set; }

    public DateTime DatumRezervacije { get; set; }

    public int BrojMjesta { get; set; }

    public virtual Korisnik IdKorisnikNavigation { get; set; }

    public virtual Putovanje IdPutovanjeNavigation { get; set; }
}