// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApp.Models;

public partial class Smjestaj
{
    public int IdSmjestaj { get; set; }

    public int IdObrok { get; set; }

    public int IdSoba { get; set; }

    public int IdVrstaSmjestaja { get; set; }

    public string Naziv { get; set; }

    public virtual Obrok IdObrokNavigation { get; set; }

    public virtual Soba IdSobaNavigation { get; set; }

    public virtual VrstaSmjestaja IdVrstaSmjestajaNavigation { get; set; }

    public virtual ICollection<Putovanje> Putovanjes { get; set; } = new List<Putovanje>();
}