// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApp.Models;

public partial class Soba
{
    public int IdSobe { get; set; }

    public string VrstaSobe { get; set; }

    public virtual ICollection<Smjestaj> Smjestajs { get; set; } = new List<Smjestaj>();
}