// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApp.Models;

public partial class Vozilo
{
    public int IdVozila { get; set; }

    public string VrstaVozila { get; set; }

    public virtual ICollection<Putovanje> Putovanjes { get; set; } = new List<Putovanje>();
}