// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApp.Models;

public partial class VrstaSmjestaja
{
    public int IdVrstaSmjestaja { get; set; }

    public string VrstaSmjestaja1 { get; set; }

    public virtual ICollection<Smjestaj> Smjestajs { get; set; } = new List<Smjestaj>();
}